@startuml analysis

class Mastermind{  

    + start()
    - showTitle()    
}
Mastermind *--> Game
Mastermind *--> YesNoDialog

class Game{
    - VALID_COLORS
    - COMBINATION_LENGTH    
    - MAX_ATTEMPTS

    + play()        
    - isEndGame()    
    - isLastProposedWinner()
    - show()
    - showEndMsg()
}
Game *--> SecretCombination
Game *--> "0..10" ProposedCombination
Game ..> Result

class SecretCombination{
    - String colors
    
    + SecretCombination(VALID_COLORS, COMBINATION_LENGTH)    
    + getResult(proposed)
    + show()
    - hasColor(searched)
}
SecretCombination .down.> ProposedCombination
SecretCombination .down.> Result

class ProposedCombination{
    - String colors    

    + ask(VALID_COLORS, COMBINATION_LENGTH)   
    + getColor(index)
    + getLength()    
    + show() 
    - isValid(VALID_COLORS, COMBINATION_LENGTH)
    - hasValidLength(COMBINATION_LENGTH)
    - hasValidColors(VALID_COLORS)
    - hasUniqueColors()
    - getErrorMsg(VALID_COLORS, COMBINATION_LENGTH)
}

class Result{
    -blacks
    -whites

    + initResult(blacks, whites)
    + isWinner(expectedBlacks)
    + show()    
}

class YesNoDialog {
    - question
    - answer
    - VALID_ANSWERS

    +YesNoDialog(question)
    + ask()
    + isAffirmative()
    - getAffirmative()
    - getNegative()
}
@enduml