@startuml analysis

class Mastermind{  

    + initMastermind()
    + play()    
}
Mastermind ..> Game
Mastermind *--> YesNoDialog

class Game{
    - VALID_COLORS
    - COMBINATION_LENGTH    
    - MAX_ATTEMPTS

    + initGame()
    + play()      
}
Game *--> SecretCombination
Game *--> "0..10" ProposedCombination
Game .down.> Result

class SecretCombination{
    - String colors
    
    + initSecretCombination(VALID_COLORS, COMBINATION_LENGTH)    
    + getResult(proposed)
    + show()    
}
SecretCombination .down.> ProposedCombination
SecretCombination .down.> Result

class ProposedCombination{
    - String colors    

    + initProposedCombination()
    + ask(VALID_COLORS, COMBINATION_LENGTH)   
    + getColor(index)
    + show() 
}

class Result{
    - blacks
    - whites
    - winnerBlacks

    + initResult(blacks, whites, winnerBlacks)
    + isWinner()
    + show()    
}

class YesNoDialog {
    - YES
    - NO
    - question
    - answer    

    + initYesNoDialog(question)
    + ask()
    + isAffirmative()
}
@enduml