@startuml develop process

state languageChoice <<choice>>

state WITH_JavaScript as " " : init JS developement  
state T1 as "T1_DONE " : branch js_v0.0
state T2 as "T2_DONE " : branch js_v0.1

[*] --> languageChoice : chooseLanguage
languageChoice -right-> WITH_JavaScript : [isJavascriptChoosed]
WITH_JavaScript --> T1 : doTask1
T1 --> T2 : doTask2
T2 --> [*]

note right of T1
Version: 
    Basic
Mathematic Fundament 
    Paradigm: Imperative
Organization Paradigm : 
    Process Oriented Programming 
Notes: 
    <b>use objects is not allowed</b>
endnote

note right of T2
Version: 
    Basic
Mathematic Fundament 
    Paradigm: Imperative
Organization Paradigm : 
    Process Oriented Programming    
Notes: 
    objects can be used, but only <b>as structs</b> 
        -> without methods
endnote

@enduml